[package]
name = "webview_yew_minimal_frontend"
version = "0.1.0"
authors = ["mbuscemi <matthew.buscemi@gmail.com>"]
edition = "2018"

[dependencies]
yew = { version = "0.15.0", package = "yew-stdweb" }
stdweb = "0.4.20"
serde = "1.0.106"
serde_json = "1.0.51"
serde_derive = "1.0.106"